library(XML)
library(rlist)
library(sjmisc)
library(stringr)
library(gdata)
library(stringr)
library(RJSONIO)
library(RCurl)
library(rvest)
library(neuralnet)

source("C:\\Users\\sowin\\OneDrive\\collegebball\\yest_results.R")
source("C:\\Users\\sowin\\OneDrive\\collegebball\\today_predictions.R")
source("C:\\Users\\sowin\\OneDrive\\collegebball\\train_model.R")
source("C:\\Users\\sowin\\OneDrive\\collegebball\\get_stats.R")

yest_results()
today_predictions()
overall_stats <- get_overall_stats()
month_stats <- get_month_stats()
